<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Siswa;

class SiswaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // 10 siswa Techno
            [
                'id_siswa' => '41',
                'nama_siswa' => 'Ahmad Budi',
                'nisn' => '100001',
                'level' => 'VII',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Budi',
                'no_hp_wali' => '081234567001',
            ],
            [
                'id_siswa' => '42',
                'nama_siswa' => 'Dewi Lestari',
                'nisn' => '100002',
                'level' => 'VII',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Lestari',
                'no_hp_wali' => '081234567002',
            ],
            [
                'id_siswa' => '43',
                'nama_siswa' => 'Rudi Hartono',
                'nisn' => '100003',
                'level' => 'VIII',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Hartono',
                'no_hp_wali' => '081234567003',
            ],
            [
                'id_siswa' => '44',
                'nama_siswa' => 'Sari Melati',
                'nisn' => '100004',
                'level' => 'VIII',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Melati',
                'no_hp_wali' => '081234567004',
            ],
            [
                'id_siswa' => '45',
                'nama_siswa' => 'Bambang Setiawan',
                'nisn' => '100005',
                'level' => 'VIII',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Setiawan',
                'no_hp_wali' => '081234567005',
            ],
            [
                'id_siswa' => '46',
                'nama_siswa' => 'Nina Anggraini',
                'nisn' => '100006',
                'level' => 'VIII',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Anggraini',
                'no_hp_wali' => '081234567006',
            ],
            [
                'id_siswa' => '47',
                'nama_siswa' => 'Iqbal Ramadhan',
                'nisn' => '100007',
                'level' => 'IX',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Ramadhan',
                'no_hp_wali' => '081234567007',
            ],
            [
                'id_siswa' => '48',
                'nama_siswa' => 'Putri Wulandari',
                'nisn' => '100008',
                'level' => 'IX',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Wulandari',
                'no_hp_wali' => '081234567008',
            ],
            [
                'id_siswa' => '49',
                'nama_siswa' => 'Agus Pranoto',
                'nisn' => '100009',
                'level' => 'IX',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Pranoto',
                'no_hp_wali' => '081234567009',
            ],
            [
                'id_siswa' => '50',
                'nama_siswa' => 'Fitriani Zahra',
                'nisn' => '100010',
                'level' => 'IX',
                'kategori' => 'Tidak boarding',
                'akademik' => 'Techno',
                'nama_wali' => 'Zahra',
                'no_hp_wali' => '081234567010',
            ],

            // 10 siswa Praxis
        //     [
        //         'id_siswa' => '11',
        //         'nama_siswa' => 'Ali Fauzi',
        //         'nisn' => '100011',
        //         'level' => 'X',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Fauzi',
        //         'no_hp_wali' => '081234567011',
        //     ],
        //     [
        //         'id_siswa' => '12',
        //         'nama_siswa' => 'Maya Sari',
        //         'nisn' => '100012',
        //         'level' => 'X',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Sari',
        //         'no_hp_wali' => '081234567012',
        //     ],
        //     [
        //         'id_siswa' => '13',
        //         'nama_siswa' => 'Dedi Kurniawan',
        //         'nisn' => '100013',
        //         'level' => 'XII',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Kurniawan',
        //         'no_hp_wali' => '081234567013',
        //     ],
        //     [
        //         'id_siswa' => '14',
        //         'nama_siswa' => 'Citra Rahma',
        //         'nisn' => '100014',
        //         'level' => 'X',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Rahma',
        //         'no_hp_wali' => '081234567014',
        //     ],
        //     [
        //         'id_siswa' => '15',
        //         'nama_siswa' => 'Eka Putra',
        //         'nisn' => '100015',
        //         'level' => 'XI',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Putra',
        //         'no_hp_wali' => '081234567015',
        //     ],
        //     [
        //         'id_siswa' => '16',
        //         'nama_siswa' => 'Rina Oktaviani',
        //         'nisn' => '100016',
        //         'level' => 'XII',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Oktaviani',
        //         'no_hp_wali' => '081234567016',
        //     ],
        //     [
        //         'id_siswa' => '17',
        //         'nama_siswa' => 'Fajar Nugraha',
        //         'nisn' => '100017',
        //         'level' => 'X',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Nugraha',
        //         'no_hp_wali' => '081234567017',
        //     ],
        //     [
        //         'id_siswa' => '18',
        //         'nama_siswa' => 'Linda Mawar',
        //         'nisn' => '100018',
        //         'level' => 'XI',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Mawar',
        //         'no_hp_wali' => '081234567018',
        //     ],
        //     [
        //         'id_siswa' => '19',
        //         'nama_siswa' => 'Taufik Hidayat',
        //         'nisn' => '100019',
        //         'level' => 'XII',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Hidayat',
        //         'no_hp_wali' => '081234567019',
        //     ],
        //     [
        //         'id_siswa' => '20',
        //         'nama_siswa' => 'Nur Aini',
        //         'nisn' => '100020',
        //         'level' => 'XI',
        //         'kategori' => 'Tidak boarding',
        //         'akademik' => 'Praxis',
        //         'nama_wali' => 'Aini',
        //         'no_hp_wali' => '081234567020',
        //     ],
        ];

        foreach ($data as $siswa) {
            Siswa::create($siswa);
        }
    }
}
